[package]
name = "teras_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.12"
dama = "0.1.0"
arrayvec = "0.7.6"
bytemuck = { version = "1.22.0", features = ["derive"] }
crossbeam = "0.8.4"
